### ISSUE TITLE
Spelling error in 'Focus on artboard' option

### ISSUE THREAD

**Issue by bcorporaal** [jacopocolo/p5-sketchplugin#14]
The word 'artboard' is missing an r ;-)
<img width="139" alt="p5" src="https://user-images.githubusercontent.com/12683014/32631933-11c52fd0-c5a2-11e7-9da6-406a203b1af6.png">

**Comment by jacopocolo** [comment]
🙈 I’m so ashamed. It has been staring at me for months and I didn't notice. 

Thanks, I’ll fix it 🙄

**Comment by jacopocolo** [comment]
Fixed in upcoming 1.1.0
