### ISSUE TITLE
Remote 'Get' from Reference, or build support for it 😊 

### ISSUE THREAD

**Issue by songcarver** [jacopocolo/p5-sketchplugin#16]
https://github.com/jacopocolo/p5-sketchplugin#reference
has a reference to Get which links to the general Color overview. AFAICT, get is (understandably) not currently supported. 

Suggestion, removing Get() from that https://github.com/jacopocolo/p5-sketchplugin#reference
to avoid confusions like these. Thanks!

**Comment by jacopocolo** [comment]
Removing it for now. I had to take it out last minute because it crashed Sketch 48 beta. It’s coming back in the next release! 

Thanks for pointing this out :)

**Comment by songcarver** [comment]
Looking forward to next release! Think we can build some pretty cool things!

**Comment by songcarver** [comment]
+1 to keep it on the list for next release 🙏
