### ISSUE TITLE
[Suggestion] Possibility to resize the window

### ISSUE THREAD

**Issue by lanceplaine** [jacopocolo/p5-sketchplugin#3]
Currently it doesn't seems possible to resize the window

<img width="725" alt="screen shot 2017-09-22 at 4 40 22 pm" src="https://user-images.githubusercontent.com/5476205/30767791-dd9f4be0-9fb4-11e7-845b-a3e44662dc1e.png">

**Comment by jacopocolo** [comment]
Didn't think it was possible but… it's possible 🎉  
Coming with the next release.

**Comment by lanceplaine** [comment]
👏
