### ISSUE TITLE
[Suggestion] Possibility to move the window using the whole top area

### ISSUE THREAD

**Issue by lanceplaine** [jacopocolo/p5-sketchplugin#6]
Currently moving the window is a little bit annoying since the only the very top area (blue box in the drawing) allow me to drag the window. If would be great if the whole top area (blue+green boxes in the drawing) works like most of the macOS apps.

<img width="690" alt="screen shot 2017-09-22 at 4 52 44 pm copy" src="https://user-images.githubusercontent.com/5476205/30767970-ad08b21c-9fb6-11e7-854d-063009eaea8f.png">

**Comment by jacopocolo** [comment]
I’m afraid this is not possible. Technically the part below is an HTML page I’m loading with a webview so it doesn't behave like a macOS app. What I could do is make the header (the blue area) more distinguished  by using the default look of simple macOS windows. I’ll think about it.

**Comment by lanceplaine** [comment]
Yes I think that at least using the default macOS style for the blue area should help :)

**Comment by jacopocolo** [comment]
I tweaked the UI in release 0.9.4 to suggest that there's a top bar like in normal windows, it doesn't solve the issue completely but should help ease it. I tried the default look but I didn't like it. 

Closing this for now.

**Comment by lanceplaine** [comment]
👍
